---
name: Test Docker image reproducibility

"on":
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha256: ${{ steps.hash.outputs.sha256 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v6.15.0
        with:
          push: false
          load: true
          outputs: type=docker,dest=image.tar,rewrite-timestamp=true
          provenance: false
        env:
          SOURCE_DATE_EPOCH: 0

      - name: Compute SHA256
        id: hash
        run: echo "sha256=$(sha256sum image.tar | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Report image hash
        run: |
          echo "Hash from the second image build: ${{ steps.hash.outputs.sha256 }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-image-tar
          path: image.tar

  rebuild:
    runs-on: ubuntu-latest
    outputs:
      sha256: ${{ steps.hash.outputs.sha256 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          outputs: type=docker,dest=image.tar,rewrite-timestamp=true
          provenance: false
        env:
          SOURCE_DATE_EPOCH: 0

      - name: Compute SHA256
        id: hash
        run: echo "sha256=$(sha256sum image.tar | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Report image hash
        run: |
          echo "Hash from the second image build: ${{ steps.hash.outputs.sha256 }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rebuild-image-tar
          path: image.tar

  reproducibility:
    name: Check reproducibility
    runs-on: ubuntu-latest
    needs:
      - build
      - rebuild
    steps:
      - name: Fail if empty
        if: ${{ needs.build.outputs.sha256 == '' }}
        run: |
          echo needs.build.outputs.sha256 is ${{ needs.build.outputs.sha256 }}
          exit 1
      - name: Report image Hash
        run: |
          echo "Hash from the first image build: ${{ needs.build.outputs.sha256 }}"
          echo "Hash from the second image build: ${{ needs.rebuild.outputs.sha256 }}"

      - name: Check if match
        if: ${{ needs.build.outputs.sha256 != needs.rebuild.outputs.sha256 }}
        run: |
          echo ${{ needs.build.outputs.sha256 }} != ${{ needs.rebuild.outputs.sha256 }}
          echo Image is not reproducible
          echo "::error::Image is not reproducible"
          exit 1

  diffoscope:
    name: Report difference
    needs:
      - build
      - rebuild
    if: ${{ needs.build.outputs.sha256 != needs.rebuild.outputs.sha256 }}
    runs-on: ubuntu-24.04
    container:
      # latest at 2025-05-03
      image: registry.salsa.debian.org/reproducible-builds/diffoscope@sha256:9a6780b2a83f885ae917043d0dd71038d70bebd56dd8d24d00d7de91da7a8454
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-image-tar
          path: build

      - name: Download rebuild artifact
        uses: actions/download-artifact@v4
        with:
          name: rebuild-image-tar
          path: rebuild

      - name: Run diffoscope
        run: diffoscope build/image.tar rebuild/image.tar --fuzzy-threshold 400 --html report.html --output-empty

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
